version: "3"
services:
  api:
    image: nginx:latest
    ports:
      - 3000:3000
    volumes:
      - ./docker/api/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
  php-fpm:
    build: ./docker/php-fpm
    volumes:
      - ./source/api:/var/www/html
      - dbsocket:/var/run/mysqld
    environment:
      DB_CONNECTION: mysql
      DB_HOST: localhost
      DB_PORT: 3306
      DB_DATABASE: testdb
      DB_USERNAME: user
      DB_PASSWORD: password
      DB_SOCKET: /var/run/mysqld/mysqld.sock
    depends_on:
      - db
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: testdb
    volumes:
      - ./db-data:/var/lib/mysql
      - dbsocket:/var/run/mysqld
  node:
    build: ./docker/web
    volumes:
      - ./source/web:/app
    ports:
      - 8080:8080
    command: sh -c "npm i && npm start"
volumes:
  dbsocket: