version: "3"
services:
  api:
    image: nginx:latest
    ports:
      - 3000:3000
    volumes:
      - ./docker/api/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
  php-fpm:
    image: php:7.3-fpm-alpine
    volumes:
      - ./source/api:/var/www/html
    depends_on:
      - db
  db:
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: testdb
    volumes:
      - ./db-data:/var/lib/mysql
  node:
    build: ./docker/web
    volumes:
      - ./source/web:/app
    ports:
      - 8080:8080
    command: sh -c "npm i && npm start"